<#
.SYNOPSIS
    Regenerates the winget HRESULT lookup table from the installed winget.

.DESCRIPTION
    Runs `winget error --output` to get winget's own return code table, parses every markdown
    row, and writes WingetErrorCodes.g.cs. Run this after a winget upgrade adds codes.

.PARAMETER OutputPath
    Full path of the C# file to write. Defaults to the file the app compiles.

.EXAMPLE
    ./tools/Update-WingetErrorCodes.ps1

    Rewrites src/WingetNudge.Core/Packages/WingetErrorCodes.g.cs from the installed winget.

.OUTPUTS
    System.String
        Full path of the file written.

.NOTES
    Requires winget 1.9 or newer, which is where `winget error` landed.
#>
[CmdletBinding(SupportsShouldProcess)]
[OutputType([string])]
param(
    [ValidateNotNullOrWhiteSpace()]
    [string]$OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath '../src/WingetNudge.Core/Packages/WingetErrorCodes.g.cs')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ///// Capture winget's table /////

[string]$tableFile = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "winget-errors-$([guid]::NewGuid()).md"
try {
    # Its stdout is compiled into shipped source, so resolve the executable rather than trust PATH.
    [string]$winget = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\winget.exe'
    if (-not (Test-Path -Path $winget -PathType Leaf)) {
        $winget = (Get-Command -Name 'winget.exe' -CommandType Application -ErrorAction Stop).Source
    }

    & $winget error --output $tableFile | Out-Null
    if (-not (Test-Path -Path $tableFile -PathType Leaf)) {
        throw "winget error produced no file at $tableFile."
    }

    [string[]]$lines = Get-Content -Path $tableFile
} finally {
    Remove-Item -Path $tableFile -ErrorAction Ignore
}

# ///// Parse the rows /////

# Each data row is: | 0x8A150001 | -1978335231 | SYMBOL | Description |
[regex]$rowPattern = [regex]::new('^\|\s*(0x[0-9A-Fa-f]{8})\s*\|\s*-?\d+\s*\|\s*([A-Z0-9_]+)\s*\|\s*(.+?)\s*\|$')

[System.Collections.Generic.List[PSCustomObject]]$codes = @()
[System.Collections.Generic.HashSet[string]]$seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($line in $lines) {
    [System.Text.RegularExpressions.Match]$match = $rowPattern.Match($line)
    if (-not $match.Success) {
        continue
    }

    [string]$hex = $match.Groups[1].Value.ToUpperInvariant().Replace('0X', '0x')
    if (-not $seen.Add($hex)) {
        continue
    }

    $codes.Add([PSCustomObject]@{
        Hex         = $hex
        Symbol      = $match.Groups[2].Value
        Description = $match.Groups[3].Value
    })
}

if ($codes.Count -eq 0) {
    throw 'Parsed no error codes; winget changed its output format.'
}

Write-Verbose "Parsed $($codes.Count) winget error codes."

# ///// Emit the C# file /////

[System.Text.StringBuilder]$source = [System.Text.StringBuilder]::new()
[void]$source.AppendLine('// Auto-generated by tools/Update-WingetErrorCodes.ps1. Do not edit.')
[void]$source.AppendLine()
[void]$source.AppendLine('#nullable enable')
[void]$source.AppendLine()
[void]$source.AppendLine('using System.Collections.Frozen;')
[void]$source.AppendLine()
[void]$source.AppendLine('namespace WingetNudge.Core.Packages;')
[void]$source.AppendLine()
[void]$source.AppendLine('/// <summary>One winget return code.</summary>')
[void]$source.AppendLine('/// <param name="Symbol">Winget''s symbolic name, such as <c>APPINSTALLER_CLI_ERROR_INTERNAL_ERROR</c>.</param>')
[void]$source.AppendLine('/// <param name="Description">Winget''s own one-line description.</param>')
[void]$source.AppendLine('public sealed record WingetErrorCode(string Symbol, string Description);')
[void]$source.AppendLine()
[void]$source.AppendLine('/// <summary>Winget''s return codes, as reported by <c>winget error</c>.</summary>')
[void]$source.AppendLine('public static class WingetErrorCodes')
[void]$source.AppendLine('{')
[void]$source.AppendLine('    private static readonly FrozenDictionary<int, WingetErrorCode> Codes =')
[void]$source.AppendLine('        new Dictionary<int, WingetErrorCode>')
[void]$source.AppendLine('        {')

foreach ($code in $codes) {
    [string]$escaped = $code.Description.Replace('\', '\\').Replace('"', '\"')
    [void]$source.AppendLine("            [unchecked((int)$($code.Hex))] = new(`"$($code.Symbol)`", `"$escaped`"),")
}

[void]$source.AppendLine('        }.ToFrozenDictionary();')
[void]$source.AppendLine()
[void]$source.AppendLine('    /// <summary>Looks up a winget return code.</summary>')
[void]$source.AppendLine('    /// <param name="hresult">HRESULT reported by winget.</param>')
[void]$source.AppendLine('    /// <returns>The code, or <c>null</c> when winget does not define it.</returns>')
[void]$source.AppendLine('    public static WingetErrorCode? Find(int hresult) =>')
[void]$source.AppendLine('        Codes.TryGetValue(hresult, out WingetErrorCode? code) ? code : null;')
[void]$source.AppendLine('}')

[string]$resolved = [System.IO.Path]::GetFullPath($OutputPath)
if ($PSCmdlet.ShouldProcess($resolved, "Write $($codes.Count) winget error codes")) {
    [System.IO.File]::WriteAllText($resolved, $source.ToString().Replace("`r`n", "`n"))
    Write-Output $resolved
}
